#!/bin/bash

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install git
sudo apt-get -y install apache2
sudo apt-get -y install php7.0 libapache2-mod-php7.0 php7.0-mbstring php7.0-mcrypt php7.0-cgi php7.0-cli php7.0-common php7.0-curl php7.0-dom 
sudo apt-get -y install php7.0-zip 
sudo phpenmod mcrypt
sudo phpenmod mbstring 
sudo a2enmod rewrite
sudo service apache2 restart
sudo curl -sS https://getcomposer.org/installer | php
sudo mv composer.phar /usr/local/bin/composer
cd /var/www/html
sudo composer install
sudo composer update




